Reordering Logic
URI-ABD/clam pull request #105
Opened 2023-06-04 17:19 UTC by olwmc

2023-06-06 22:16 UTC, olwmc commented on src/distances/u32.rs
> +pub const METRICS: [(&str, fn(&[u32], &[u32]) -> f32); 2] = [
This exists to make the `Dataset` tests work without chance of floating point error. This could be removed/modified without issue.

2023-06-09 17:30 UTC, nishaq503 requested changes
This looks good for the most part. Most of my comments are in `cluster.rs`. Once you've taken care of those and have removed mention of `Cluster` from public doc strings, we can merge this PR.

2023-06-09 17:30 UTC, nishaq503 commented on src/core/cluster.rs
> +    t: std::marker::PhantomData<T>,
Rename this to `_t`

2023-06-09 17:30 UTC, nishaq503 commented on src/core/cluster.rs
> +    /// this does not build nor partition the underlying `Cluster`
Do not expose `Cluster` even in doc strings

2023-06-09 17:30 UTC, nishaq503 commented on src/core/cluster.rs
> +    children: Option<([(usize, Box<Cluster<T, U, D>>); 2], U)>,
Add a TODO here to later simplify the type using a `Children` struct

2023-06-09 17:30 UTC, nishaq503 commented on src/core/cluster.rs
> +    pub fn new_root(data: &D, indices: Vec<usize>, seed: Option<u64>) -> Self {
Have the `indices` input parameter be of type `&[usize]`. Also see `Cluster::new`

2023-06-09 17:30 UTC, nishaq503 commented on src/core/cluster.rs
> +    pub fn new(data: &D, indices: Vec<usize>, history: BitVec, seed: Option<u64>) -> Self {
Change the type of `indices` to `&[size]` and call `.to_vec()` when instantiating the `Cluster`

2023-06-09 17:30 UTC, nishaq503 commented on src/core/cluster.rs
> +            index: Index::Indices(indices),
Call `.to_vec()` on `indices` here

2023-06-09 17:30 UTC, nishaq503 commented on src/core/cluster.rs
> +    #[allow(unused)]
What is left unused here?

2023-06-09 17:30 UTC, nishaq503 commented on src/core/cluster.rs
>      pub fn subtree(&self) -> Vec<&Self> {
Add a line in the doc-string saying that this is a potentially expensive function.

2023-06-09 22:26 UTC, olwmc commented on src/core/cluster.rs
> +    #[allow(unused)]
Nothing! Removed.

2023-06-09 22:40 UTC, olwmc commented
## Notes:
* I gave a shot at implementing manhattan/cosine distance for `u32`. Feel free to scrap.
* I wasn't sure what to document `Tree::par_partition` with. I may need some assistance if we'd like to document that.
* I'm currently giving a shot at merging `indices` and `leaf_indices` 😎

2023-06-09 23:02 UTC, nishaq503 requested changes
The final changes I need are just to correct casting of types in the distance module

2023-06-09 23:02 UTC, nishaq503 commented on src/distances/u32.rs
> +];
Add the other two distance functions here

2023-06-09 23:02 UTC, nishaq503 commented on src/distances/u32.rs
> +    x.iter().zip(y.iter()).map(|(&a, &b)| (a - b).pow(2) as f32).sum()
cast `a` and `b` to f32 before the subtraction.

2023-06-09 23:02 UTC, nishaq503 commented on src/distances/u32.rs
> +    x.iter().zip(y.iter()).map(|(&a, &b)| a.max(b) - a.min(b)).sum()
cast here too

2023-06-09 23:02 UTC, nishaq503 commented on src/distances/u32.rs
> +        .fold([0; 3], |[xx, yy, xy], (&a, &b)| [xx + a * a, yy + b * b, xy + a * b]);
and here

2023-06-10 01:24 UTC, nishaq503 approved these changes
LGTM

2023-06-10 01:25 UTC, merged