Feat/dataset save load
URI-ABD/clam pull request #146
Opened 2023-10-02 20:12 UTC by olwmc

Implements `save` and `load` functionality for `vec2d`. Serializes into a simple binary format.

## TODO
- [ ] Improve filthy low level file parsing code where applicable
- [ ] Comments

2023-10-04 20:43 UTC, nishaq503 requested changes
This looks very good. There are two changes that I'd like to see:

- Update the `distances` dependency to version `1.4.1` and then use the `type_name` method as part of the header.
- Use the `tempdir` [crate](https://docs.rs/tempdir/latest/tempdir/) as a dev-dependency for the tests.

2023-10-04 20:43 UTC, nishaq503 commented on abd-clam/src/core/dataset/vec2d.rs
> +            .map_err(|err| format!("{err}"))?;
Include the `type_name` after this. I just added the method to the `Number` trait. You'll have to update the dependency on `distances` to `1.4.1`.

2023-10-04 20:43 UTC, nishaq503 commented on abd-clam/src/core/dataset/vec2d.rs
> +        let type_size = std::mem::size_of::<V>();
Change this in accordance with the `type_name` that you will have written. Ideally, you would check to see that the name matches and then use the `num_bytes` method on `Number`.

2023-10-04 20:43 UTC, nishaq503 commented on abd-clam/src/core/dataset/vec2d.rs
> +        dataset.save(&std::env::temp_dir().join("datset.save")).unwrap();
Add and use the `tempdir` [crate](https://docs.rs/tempdir/latest/tempdir/) as a dev dependency.

2023-10-05 20:48 UTC, olwmc commented
Changes made. Random test changed a little bit to speed it up a little bit.

2023-10-06 02:39 UTC, nishaq503 submitted a review, later dismissed
LGTM

2023-10-06 14:46 UTC, merged