Minor refactor for dataset
URI-ABD/clam pull request #99
Opened 2023-04-03 00:35 UTC by olwmc

*Assigned to me by Najib*

# Overview
This PR contains a minor refactor, pulling the geometric median calculation logic out of `Cluster` and making it a method in the `Dataset` trait.

# Comments
Originally it was talked about moving the calculations for some of the other properties calculated in `Cluster::build` out into their own methods. I wasn't sure if this was still the case after reviewing the video from our original meeting. If this is the case, let me know I'll pull them out.

2023-04-05 18:58 UTC, nishaq503 requested changes
This looks good. Here are a couple of changes I want to see:

- Move the implementation of `median` into the trait itself. Then add to the documentation that the default implementation is not scalable (for now) to an arbitrarily large input.
- Add a panic condition to the docs for when `indices` is a zero-length slice.

Once these are done, the PR will be ready.

2023-04-07 18:18 UTC, olwmc commented
- [X] ~Move the implementation of median into the trait itself. Then add to the documentation that the default implementation is not scalable (for now) to an arbitrarily large input~
- [X] ~Add a panic condition to the docs for when `indices` is a zero-length slice.~

Finished. I wasn't sure what would be the best way to represent two notes stylistically, so I grouped them into a subheader (h2). This could be easily changed.

2023-04-08 02:31 UTC, nishaq503 approved these changes
This looks good. Squash the commits down to one and I'll merge it in.

2023-04-08 16:40 UTC, olwmc commented
This should be good 😎

2023-04-08 16:41 UTC, merged